### ISSUE TITLE
Add an option to checkOnly

### ISSUE THREAD

**Issue by mar10** [darsain/grunt-tagrelease#2]
Your code already checks, if the tag already exists, and fails with `Warning: Version "2.0.0-22" is lower or equal than the current highest tag "2.0.0-22"`, which is good!

But at that point in my build process I already have overwritten the /build folder and 'dist/foo-2.0.0-22.zip'.
So I would like to run the tagrelease in a check-only mode as one of the first tasks in the build chain.

Another (optional) check could be `assertClean`, which fails if there a uncommitted changes.
The reason is, that I don't want to accidentally commit feature changes with a message  like 'Release 2.0.0-22'.
Of course I would run this check before bumpup or replace version token tasks, since these modifications are part of the release process.

**Comment by darsain** [comment]
This seems like something that should be in a separate Grunt task. tagrelease is for tagging the release, not validating the repository state.

Besides, tagrelease is not a multitask, so this would mean rewriting it into multitask format, which would take away the simplicity of current config.

**Comment by mar10** [comment]
(I am new to this node/grunt stuff, so I may be plain wrong):
the grunt-contrib-\* suite seems to be multitask, but also allows the simplicty of single task syntax(?)
In my opinion 'simplicity' means 'works as expected (if there is s.th. like a standard)', so adding multitask may be a good thing anyway.

I agree that trying to accomplish too much in one task would break the idea of having simple building blocks, that can be assembled in one grunt script.  
But I want to check if `tagrelease` _would_ run before I start the build process, so I would have to write a separate task that performs the identical tests - only without performing the action. This is probably easy, but this checks should ideally be synchronized with the real `tagrelease` behavior if it is updated sometime.  
So I am still +1 for the `checkOnly` feature ;-)

However I am not sure if this `assertClean` feature is really useful. Maybe that should be a simple separate task.

**Comment by darsain** [comment]
I've thought about it, and adding all this stuff to tagrelease would just bastardize it. Again, checking/validating repository state is outside of the scope of this task.

But I've written task that will do just that. Try it out:
https://github.com/Darsain/grunt-checkrepo

I'm closing this issue. If there will be problems with checkrepo, use its issue tracker instead.

**Comment by mar10** [comment]
cool! will try it the next days.

**Comment by mar10** [comment]
Worked well for me, thanks!

Two ideas I had (just brainstorming, I don't currently need these features, so I won't open issues):
- check for file or folder existence (e.g. `isFile`, ..)
- allow to handle errors as warnings that result in a prompt 'Continue anyway Y/n?'

**Comment by darsain** [comment]
> check for file or folder existence (e.g. isFile, ..)

That would be a separate plugin. I'd be surprised if it didn't exist yet. I'm not doing it.

> allow to handle errors as warnings that result in a prompt 'Continue anyway Y/n?'

Handling of errors is done by Grunt, not plugins/tasks. And you can do `--force` to ignore errors and run every task in queue.
